
[tool.mypy]
plugins = "pydantic.mypy"
python_version = "3.12"
disable_error_code = [
    "import-untyped",
    "annotation-unchecked",
    "literal-required",
]
namespace_packages = true

[tool.ruff]
exclude = [
    ".conda",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    ".git",
    ".idea",
    "./playground.py",
    "./logs",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
lines-between-types = 1
no-sections = true
